### ISSUE TITLE
module "QtQuick" version 2.7 is not installed

### ISSUE THREAD

**Issue by ThomasSeeker** [Koffeinfriedhof/gealach#5]
If I try to install, this is what I get: "module "QtQuick" version 2.7 is not installed".
I looked for QtQuick-packages to install, but there are countless of them. Which one should I install?
I'm running Linux Mint KDE 18.3.

**Comment by Koffeinfriedhof** [comment]
Please ask in forums of your distribution concerning Qt-Packaging, if possible. If they could not help you, you may ask here again ;)
